// app/create-post/page.tsx
import React from "react";
import BlogPostForm from "@/components/BlogPostForm";
import { getCategory } from "@/actions";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Blog | JourneyVerse",
  description: "Generated by create next app",
};

const CreatePost = async () => {
  const data = await getCategory();

  return (
    <div>
      <BlogPostForm initialData={null} categories={data} />
    </div>
  );
};

export default CreatePost;
