import React from "react";
import type { Metadata } from "next";
import { getProviders } from "next-auth/react";
import Login from "@/components/Login";

export const metadata: Metadata = {
  title: "Login | JourneyVerse",
  description: "Generated by create next app",
};

const SignIn = async () => {
  return (
    <div>
      <Login />
    </div>
  );
};

export default SignIn;
